### ISSUE TITLE
Ideas to implement 

### ISSUE THREAD

**Issue by Dan8NOD** [scorellis/NOD-ify#1]
Add elevation 
Minimum encourages

Vision labels 

Advanced label
Tonality -

**Comment by Dan8NOD** [comment]
(add this as a new tool) Elevation
Description: 
Works well on Assertives and Accomodators. Analyticals might see it as a tactic. 

(modify tool description) Trigger: 

(add) minimal encourages 

(add to Labels description)  a negative label is worth 7x. Address the negatives first. "its not a sin to get a bad deal... it's a sin to take along time" 

(add) asking label- too many questions can agitate your counterpart. 

(add) mis label- Try and limit to 3 of these. Its a potent tool to elicit information. People have correction addiction.

(add) vision label - can execute with a Calibrated Questions. What projects are you working on?

**Comment by Dan8NOD** [comment]
(add) advanced label- " I get the sense that...... " Tonality is critical with this tool

**Comment by scorellis** [comment]
completed. Please review and open new issues if you have any issues.
